media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/data/post
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: publishDate, label: Date, type: string }
      - { name: title, label: Title, type: string, required: true }
      - { name: image, label: Featured image, type: string}
      - { name: category, label: Category, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: excerpt, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: pages
    label: Pages
    type: collection 
    path: src/pages
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
      